---
title: "Sensitivity analyses"
author: "Derek Benson"
date: "2024-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Packages required for sensitivity analysis
#install.packages("sensiPhy")
library(sensiPhy)
```

```{r}
library(AICcmodavg)
library(ape)
library(caper)
library(car)
library(coda)
library(extrafont)
library(geiger)
library(kableExtra)
library(MuMIn)
library(nlme)
library(pbapply)
library(phylopath)
library(phytools)
library(plotrix)
library(rphylopic)
library(scales)
library(shape)
library(xtable)
```


#Here you need to load in the first part of the index, specifying the phylogenetic tree and dataset, below is the old example where I loaded in the data. 
```{r}
#THIS IS AN EXAMPLE, THESE FILES SHOULD BE UPDATED TO THE NEWEST FORMAT
set.seed(80)

## Dataset

data <- read.csv("C:/Users/derek/Dropbox (ASU)/Telomerase paper/Shared_Data/Revision files/analyses/new_data_2024_revision_data_seluanov corrections_names_changed.csv")
str(data)
head(data)

unique(data$Class)

dat <- data
names(dat)
dat$log_mass <- log1p(dat$Adult_mass_grams)
dat$log_mass


#dat$log.lifespan <- log(dat$Lifespan_years)
#dat$log.mass <- log1p(dat$Adult_mass_grams)
#dat <- dat[order(dat$Class), ]

#dat[dat$Scientific_name == "Pygoscelis_adeliae", ]
#dat[dat$Scientific_name == "Pteropus_rodricensis", ]
dat[dat$Average_Telomere_Length_kb > 200, ]

#str(dat)

#dat <- dat[!dat$Scientific_name == "Pygoscelis_adeliae", ] ## deleting duplicated spp
#dat <- dat[!dat$Scientific_name == "Pteropus_rodricensis", ] ## deleting duplicated spp
dat <- dat[!dat$Scientific_name == "Sorex_granarius", ] ## potential outlier


rownames(dat) <- dat$Scientific_name
head(dat)

## Trees
full_data_tree <- read.tree("C:/Users/derek/Dropbox (ASU)/Telomerase paper/Shared_Data/Revision files/analyses/full species list.nwk")
is.ultrametric(full_data_tree) 
full_data_tree <- force.ultrametric(full_data_tree) #need to load this package in, it is in the packages needed to run the full analyses but I am unsure what specific package it is.
is.ultrametric(full_data_tree)
full_data_tree

check <- name.check(full_data_tree, dat)
rm_phy <- check$tree_not_data
rm_dat <- check$data_not_tree
pruned_data_tree <- drop.tip(full_data_tree, rm_phy)
pruned_dat <- subset(dat, subset = dat$Scientific_name %in% full_data_tree$tip, select = names(dat))
str(pruned_dat)
head(pruned_dat)
full_data_tree


hist(pruned_dat$Lifespan_years, main = "raw variable")
hist(log1p(pruned_dat$Lifespan_years), main = "log-transformed")
names(pruned_dat)

pruned_dat$log.lifespan <- log1p(pruned_dat$Lifespan_years)
pruned_dat$log.lifespan

pruned_dat[1:5, 1:5]
pruned_data_tree$tip.label

pruned_dat$new.log.TL <- log(pruned_dat$Average_Telomere_Length_kb)
pruned_dat$new.log.TL
```


```{r}
# Create sensitivity analysis object using 'samp' method
samp <- samp_phylm(new.log.TL ~ log.lifespan, phy = full_data_tree, 
                   data = pruned_dat, n.sim = 1000)

summary(samp)

#For the analysis, set the number of simulations to 1000. However, for the generation of figures, the number of simulations should be set to 100, because 1000 is too many for plotting and things aren't as clean

plot1 = sensi_plot(samp, graphs = 1, param = "estimate")
dev.copy2pdf(file = "C:/Users/derek/Dropbox (ASU)/Telomerase paper/Shared_Data/Revision files/plot1.pdf", width = 7, height = 7)
plot2 = sensi_plot(samp, graphs = 2, param = "estimate")
dev.copy2pdf(file = "C:/Users/derek/Dropbox (ASU)/Telomerase paper/Shared_Data/Revision files/plot2.pdf", width = 7, height = 7)
plot3 = sensi_plot(samp, graphs = 3, param = "estimate")
dev.copy2pdf(file = "C:/Users/derek/Dropbox (ASU)/Telomerase paper/Shared_Data/Revision files/plot3.pdf", width = 7, height = 7)
plot4 = sensi_plot(samp, graphs = 4, param = "estimate")
dev.copy2pdf(file = "C:/Users/derek/Dropbox (ASU)/Telomerase paper/Shared_Data/Revision files/plot4.pdf", width = 7, height = 7)
```

